# Generated by Django 4.2.3 on 2023-07-17 15:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('snacks', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='snack',
            old_name='title',
            new_name='name',
        ),
    ]
